#!/bin/bash
BRANCH=`git branch --show-current`
if [ $BRANCH = "main" ]; then BRANCH="latest"; fi
./build-docker-image.sh Dockerfile -t ghcr.io/ptr33/paperless-ngx:$BRANCH && \
docker push ghcr.io/ptr33/paperless-ngx:$BRANCH
